# Generated by Django 3.2.5 on 2021-08-07 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='actice',
            new_name='active',
        ),
    ]
