# Generated by Django 3.2.5 on 2021-08-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0002_sitesettings_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='copy_right',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='متن کپی رایت'),
        ),
    ]
