# Generated by Django 3.2.5 on 2021-08-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0003_sitesettings_copy_right'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='copy_right',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='متن کپی رایت'),
        ),
    ]
