# Generated by Django 3.2.5 on 2021-08-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contact', '0002_alter_contactus_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='test',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده/نشده'),
        ),
    ]
